name: Lint Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/*.yml, .github/workflows/*.yaml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Workflow Files
        run: |
          docker run --rm -v $(pwd):/repo --workdir /repo rhysd/actionlint:latest -color
