name: Call

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    permissions:
      security-events: write
      checks: write
    uses: tmx-kenmotsu/.github/.github/workflows/reusable-workflow.yml@main
