name: Call

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: tmx-kenmotsu/.github/workflows/reusable-workflow.yml@main