name: CI (Reusable)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-reusable-ci:
    permissions:
      checks: write
    timeout-minutes: 60
    uses: tmx-kenmotsu/.github/.github/workflows/reusable-ci.yml@main
    with:
      buildCommand: mvn package -DskipTests=true
      staticAnalysisCommand: mvn compile spotbugs:spotbugs
      unitTestCommand: mvn test
