name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ubuntu
      run: docker version
  test2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: windows
      run: docker ps
  test3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: mad
      run: docker version
