name: Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 11
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Build Artifacts
        path: '**/*.jar'

  static-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Static Analysis
      run: echo "static-analysis"

  unit-test:
    name: Unit test
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Unit test
      run: mvn test
