name: Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -DskipTests=true
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Build Artifacts
        path: '**/*.jar'

  static-analysis:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Static Analysis with SpotBugs
      run: mvn compile spotbugs:spotbugs
    - name: Publish Test Report
      uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        path: '**/spotbugsXml.xml'
    - name: Upload Static Analysis Artifacts 
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Static Analysis Artifacts
        path: '**/spotbugsXml.xml'

  unit-test:
    needs: static-analysis
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Unit Test with JUnit
      run: mvn test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5.2.0
      with:
        report_paths: '**/TEST-*.xml'
    - name: Upload Unit Test Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Unit Test Artifacts
        path: '**/TEST-*.xml'
